package orchestrator

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var planBeadSectionRE = regexp.MustCompile(`(?m)^###\s+([a-zA-Z0-9][a-zA-Z0-9_-]*):\s+(.+)$`)

// SyncPlanningArtifacts repairs open implement beads to match required_files and writes plan.md when needed.
func SyncPlanningArtifacts(townRoot, rig string, v WorkflowValidation, forcePlan bool) (string, error) {
	if townRoot == "" || rig == "" {
		return "", fmt.Errorf("town root and rig name required")
	}
	v = v.ForActivePhase()
	var parts []string
	if repairLog, err := RepairPlanningBeadSet(townRoot, rig, v); err != nil {
		return "", err
	} else if repairLog != "" {
		parts = append(parts, repairLog)
	}
	if forcePlan || PlanningPlanMDNeedsRefresh(townRoot, rig, v) {
		wrote, err := WritePlanningPlanMD(townRoot, rig, v)
		if err != nil {
			return joinStrings(parts, "; "), err
		}
		if wrote {
			parts = append(parts, "wrote plan.md from open implement beads")
		}
	}
	return joinStrings(parts, "; "), nil
}

// PlanningPlanMDNeedsRefresh reports whether plan.md should be regenerated from bd state.
func PlanningPlanMDNeedsRefresh(townRoot, rig string, v WorkflowValidation) bool {
	v = v.ForActivePhase()
	rigDir := filepath.Join(townRoot, rig, "mayor", "rig")
	path := filepath.Join(rigDir, "plan.md")
	info, err := os.Stat(path)
	if err != nil {
		return true
	}
	if info.Size() < EffectiveMinPlanBytes(rigDir, v) {
		return true
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return true
	}
	if planPlaceholderBeadIDRE.Match(data) {
		return true
	}
	open, err := ListOpenImplementBeads(townRoot, rig, v)
	if err != nil || len(open) == 0 {
		return true
	}
	if err := ValidatePlanBeads(open, filepath.Join(rigDir, "architecture.md"), v, rig); err != nil {
		return true
	}
	pathToID, _ := openImplementPathMap(townRoot, rig, v)
	for _, want := range v.RequiredFiles {
		want = filepath.ToSlash(strings.TrimSpace(want))
		if want == "" {
			continue
		}
		id := pathToID[want]
		if id == "" {
			return true
		}
		if !planSectionCovers(data, want, id) {
			return true
		}
	}
	return false
}

func planSectionCovers(data []byte, want, id string) bool {
	for _, m := range planBeadSectionRE.FindAllStringSubmatch(string(data), -1) {
		if strings.TrimSpace(m[1]) != id {
			continue
		}
		rest := strings.TrimSpace(m[2])
		if rest == want || filepath.Base(rest) == filepath.Base(want) {
			return true
		}
	}
	return false
}

func openImplementPathMap(townRoot, rig string, v WorkflowValidation) (map[string]string, error) {
	v = v.ForActivePhase()
	open, err := ListOpenImplementBeads(townRoot, rig, v)
	if err != nil {
		return nil, err
	}
	pathToID := map[string]string{}
	for _, b := range open {
		p := NormalizePlannerBeadPath(ExtractPathFromBeadTitle(b.Title, v.BeadTitleContains), v.LayoutRoot, rig)
		if p == "" {
			continue
		}
		for _, want := range v.RequiredFiles {
			want = filepath.ToSlash(strings.TrimSpace(want))
			if want != "" && pathMatchesRequired(p, []string{want}) {
				pathToID[want] = b.ID
			}
		}
	}
	return pathToID, nil
}

// WritePlanningPlanMD writes plan.md with one ### section per required_files path and real open bead IDs.
func WritePlanningPlanMD(townRoot, rig string, v WorkflowValidation) (bool, error) {
	v = v.ForActivePhase()
	pathToID, err := openImplementPathMap(townRoot, rig, v)
	if err != nil {
		return false, err
	}
	files := OrderRequiredFilesForImplementation(v.RequiredFiles)
	if len(files) == 0 {
		return false, fmt.Errorf("no required_files in workflow profile")
	}
	var missing []string
	for _, want := range files {
		if pathToID[want] == "" {
			missing = append(missing, want)
		}
	}
	if len(missing) > 0 {
		return false, fmt.Errorf("missing open implement beads for: %s (run bead repair first)", strings.Join(missing, ", "))
	}

	rigDir := filepath.Join(townRoot, rig, "mayor", "rig")
	minBytes := EffectiveMinPlanBytes(rigDir, v)
	var b strings.Builder
	b.WriteString("# Implementation plan\n\n")
	b.WriteString("## Bead map\n\n")
	b.WriteString("_Generated by gastown planning sync (open bead IDs from `bd list`). Expand acceptance bullets if QA requires more detail._\n\n")
	for _, want := range files {
		id := pathToID[want]
		b.WriteString(fmt.Sprintf("### %s: %s\n", id, want))
		b.WriteString(fmt.Sprintf("- Scope: Implement `%s` per `architecture.md` and SPEC.md.\n", want))
		b.WriteString("- Architecture: see architecture.md (paths and data model for this file).\n")
		b.WriteString("- Acceptance:\n")
		for _, bullet := range planAcceptanceBullets(want, v) {
			b.WriteString("  - ")
			b.WriteString(bullet)
			b.WriteString("\n")
		}
		b.WriteString(fmt.Sprintf("  - Bead `%s` is closed only after verification passes.\n", id))
		b.WriteString("\n")
	}
	if v.HasPhasedDelivery() {
		id := v.ActivePhaseID()
		if id == "" {
			if p, ok := v.ActivePhase(); ok {
				id = strings.TrimSpace(p.ID)
			}
		}
		b.WriteString("## Phase context\n\n")
		b.WriteString(fmt.Sprintf("Active delivery phase `%s` only. Later phases start automatically after QA `all_passed` (or use `gt rig set-phase` to switch manually).\n\n", id))
	}
	body := b.String()
	body = padPlanningPlanMD(body, minBytes)
	path := filepath.Join(rigDir, "plan.md")
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0644); err != nil {
		return false, err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return false, err
	}
	return true, nil
}

func padPlanningPlanMD(body string, minBytes int64) string {
	if int64(len(body)) >= minBytes {
		return body
	}
	var extra strings.Builder
	extra.WriteString("## Verification notes\n\n")
	n := 0
	for int64(len(body)+extra.Len()) < minBytes {
		n++
		extra.WriteString(fmt.Sprintf("- Planning sync note %d: expand per-file acceptance in bead map sections if plan review requires more than the minimum size (%d bytes).\n", n, minBytes))
	}
	return body + extra.String()
}
